USE patient_pkt;
CREATE TABLE gi_issues_id_calculated
(
    row_names INT,
    MRNUMBER VARCHAR(20),
    DATE DATETIME,
    DAY_TYPE VARCHAR(2),
    CLINIC_CONST VARCHAR (3),
CLINIC_DIA VARCHAR (3),
CLINIC_VOM VARCHAR (3),
CLINIC_NAUSEA VARCHAR(3),
CLINIC_GAG_RETCH VARCHAR (3),
CLINIC_NISSEN VARCHAR (3),
CLINIC_DESCR_CONST VARCHAR (3000),
CLINIC_DESCR_DIA VARCHAR (3000),
CLINIC_DESCR_VOM VARCHAR (3000),
CLINIC_DESCR_NAUSEA VARCHAR (3000),
CLINIC_DESCR_GAG_RETCH VARCHAR (3000)
    
);