USE patient_pkt;
CREATE TABLE bmr_id_calculated
(
    row_names INT,
    MRNUMBER VARCHAR(20),
    DATE DATETIME,
    TIME TIME,
    DAY_TYPE VARCHAR(2),
    INSP_TEMP DECIMAL(4,2),
BARO_PRESSURE INT (4),
EXP_FLOW_TEMP INT (4),
ROOM_AIR_TEMP INT (4),
EXP_FLOW_HUM INT (4),
INSP_O2 DECIMAL (6,2),
INSP_CO2 DECIMAL (6,2),
SELECTED_FLOWMETER VARCHAR (20),
STPD_TO_BTPS VARCHAR (10),
MEASURED_O2 DECIMAL (6,2),
MEASURED_CO2 DECIMAL (6,2),
BMR_TIME DECIMAL (10,5),
VO2 DECIMAL (10,5),
VO2_KG DECIMAL (10,5),
METS DECIMAL (10,5),
VCO2 DECIMAL (10,5),
VE DECIMAL (10,5),
RQ DECIMAL (10,5),
FEO2 DECIMAL (10,5),
FECO2 DECIMAL (10,5),
REE DECIMAL (10,5)

    
);