USE patient_pkt;
CREATE TABLE seizure_data_id_research
(
	row_names INT,
    MRNUMBER VARCHAR(10),
    DATE DATETIME,
    DAY_TYPE VARCHAR(2),
    DAY_QUALITY_S VARCHAR(2),
    SEIZURE_LOAD_DAY INT(5),
    SEIZURE_NUMBER_DAY INT(5),
    SEIZURE_RESPONSE_DAY DECIMAL(6,2),
    SEIZURE_NUMBER_RESPONSE_DAY DECIMAL(6,2)
);