USE patient_pkt;
CREATE TABLE vns_id_calculated
(
    row_names INT,
     MRNUMBER VARCHAR(20),
    DATE DATETIME,
    DAY_TYPE VARCHAR(2),
MAG_ACT DECIMAL(5,2),
OUTPUT_CURR DECIMAL(5,2),
FREQUENCY DECIMAL(5,2),
PULSE_WIDTH DECIMAL(5,2),
SIGNAL_ON DECIMAL(5,2),
SIGNAL_OFF DECIMAL(5,2),
MAGNET_CURRENT DECIMAL(5,2),
MAGNET_ON DECIMAL(5,2),
MAGNET_PULSE DECIMAL(5,2),
LEAD_TEST DECIMAL(5,2)





);