USE patient_pkt;
CREATE TABLE diet_rx_id_calculated
(
    row_names INT,
     MRNUMBER VARCHAR(20),
    DATE DATETIME,
    DAY_TYPE VARCHAR(2),
ROF_PR VARCHAR(5),
REASON_FOR_CHANGE_DIET INT,
SNACK_CAL_PR DECIMAL(5,2),
SNACK_RATIO_PR DECIMAL(3,2),
SNACK_NUMBER_PR DECIMAL(2,1),
MEAL_NUMBER_PR DECIMAL(2,1),
RATIO_PR DECIMAL(3,2),
CAL_PR DECIMAL(6,2),
PRO_PR DECIMAL(3,2)


);