USE patient_pkt;
CREATE TABLE med_data_id_research
(
    row_names INT,
    MRNUMBER VARCHAR(20),
    DATE DATETIME,
    DAY_TYPE FLOAT,
    MED_LOAD_DAY FLOAT,
    MED_NUMBER_DAY FLOAT,
	MED_RESPONSE_DAY FLOAT,
    MED_NUMBER_RESPONSE_DAY FLOAT
);