USE patient_pkt;
CREATE TABLE seizure_data_id_research
(
	row_names INT,
    MRNUMBER VARCHAR(10),
    DATE DATETIME,
    DAY_TYPE FLOAT,
    DAY_QUALITY_S FLOAT,
    SEIZURE_LOAD_DAY FLOAT,
    SEIZURE_NUMBER_DAY FLOAT,
    SEIZURE_RESPONSE_DAY FLOAT,
    SEIZURE_NUMBER_RESPONSE_DAY FLOAT
);