USE patient_pkt;
CREATE TABLE med_data_id_research
(
    row_names INT,
    MRNUMBER VARCHAR(20),
    DATE DATETIME,
    DAY_TYPE VARCHAR(2),
    MED_LOAD_DAY DECIMAL(6,2),
    MED_NUMBER_DAY INT(4),
	MED_RESPONSE_DAY DECIMAL(6,2),
    MED_NUMBER_RESPONSE_DAY DECIMAL(6,2)
);